---
debian_packages: [apt-transport-https, ca-certificates, curl, software-properties-common, gnupg-agent, ufw]
docker_packages: [docker-ce, docker-ce-cli, containerd.io]
python_packages: [python3, python3-pip]
python_pip_packages: [docker, docker-compose]
