---
- name: Add docker gpg key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: a+r

- name: Add docker repository | RaspberryPi
  ansible.builtin.apt_repository:
    repo: 'deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc]  https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename | lower }} stable'
    state: present
  when: ansible_architecture == "aarch64"

- name: Add docker repository | Ubuntu
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename | lower }} stable'
    state: present
  when: ansible_architecture != "aarch64"

- name: Install docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ prepare_docker_packages }}"

- name: Enable docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: restarted

- name: Install docker-compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v{{ _docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '+x'
