---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "{{ prepare_debian_packages }}"
    - "{{ prepare_python_packages }}"

- name: Install required python packages
  ansible.builtin.pip:
    name: "{{ item }}"
    virtualenv: /home/{{ ansible_ssh_user }}/venv
  with_items:
    - docker
  when: installation_type | lower == "docker"

- name: Install required python packages
  ansible.builtin.pip:
    name: "{{ item }}"
    virtualenv: /home/{{ ansible_ssh_user }}/venv
  with_items:
    - boto3
  when: installation_type | lower == "standalone" or installation_type | lower == "docker"
