---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "{{ prepare_debian_packages }}"
    - "{{ prepare_python_packages }}"

- name: Install required python packages
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3
  loop: "{{ prepare_python_pip_packages }}"

- name: Disable dns server (temporary)
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: stopped
    enabled: false
  when: ansible_distribution == "Ubuntu"

- name: Reconfigure ubuntu dns (temporary)
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: nameserver 8.8.8.8
  when: ansible_distribution == "Ubuntu"
