---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  comments:
    min-spaces-from-content: 1
  # Required by ansible-lint
  comments-indentation: false
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    spaces: 2
    indent-sequences: true
  # Required by ansible-lint
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

ignore:
  - .git/
