---
- name: "remove PiHole folders"
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ paths }}"
  when: deployment | lower == "greenfield"
- name: "remove PiHole contaienr"
  docker_container:
    name: "{{ pi_name }}"
    state: absent