---
- name: backup PiHole files
  archive:
    path:
      - /var/pihole/dnsmasq.d/*
      - /var/pihole/pihole/*
    dest: pihole.tar.gz
    format: gz
    mode: 0755
- name: send backup to Azure
  shell: 'az storage blob upload --account-name {{ acc }} --container-name {{ cont }} --account-key "{{ key }}" --name pihole.tar.gz --file pihole.tar.gz'
  when: _azure_upload == 1
- name: send backup to Linode
  shell: 's3cmd put pihole.tar.gz s3://{{ _linode_bucket }}'
  when: _linode_upload == 1
- name: send backup to AWS
  amazon.aws.aws_s3:
    aws_access_key: "{{ _aws_access_key }}"
    aws_secret_key: "{{ _aws_secret_key }}"
    mode: put
    src: pihole.tar.gz
    object: pihole/pihole.tar.gz
    bucket: "{{ _aws_bucket }}"
  when: _aws_upload == 1
- name: remove backup from the host
  file:
    state: absent
    path: $HOME/pihole.tar.gz
  when: _azure_upload == 1 or _linode_upload == 1 or _aws_upload == 1
