---
- name: disable dns on port 53 in resolved.conf
  become: true
  ansible.builtin.lineinfile:
    state: present
    path: /etc/systemd/resolved.conf
    regexp: '^#DNSStubListener'
    line: 'DNSStubListener=no'
  when: deployment | lower == "greenfield"
- name: add PiHole dns ip
  become: true
  ansible.builtin.lineinfile:
    state: present
    path: /etc/systemd/resolved.conf
    regexp: '^#DNS'
    line: 'DNS={{ ansible_default_ipv4.address }}'
  when: deployment | lower == "greenfield"
- name: remove resolv.conf
  become: true
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  when: deployment | lower == "greenfield"
- name: create symbolic link to resolv.conf
  become: true
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  when: deployment | lower == "greenfield"
- name: start dns server
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: started
    enabled: true
  when: deployment | lower == "greenfield"
- name: remove old PiHole docker image
  docker_image:
    state: absent
    name: pihole/pihole
    tag: "v{{ _ph_restore_version }}"
  when: deployment | lower == "brownfield"
