---
- name: Create PiHole docker network
  docker_network:
    name: "{{ pi_net }}"
    state: present
  when: deployment | lower == "greenfield"
- name: Create PiHole folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  with_items:
    - "{{ pi_folders }}"
  when: deployment | lower == "greenfield"
- name: Create PiHole pihole volume
  docker_volume:
    name: pihole-db
    driver_options:
      type: none
      device: /var/pihole/pihole
      o: bind
  when: deployment | lower == "greenfield"
- name: Create PiHole config-pihole volume
  docker_volume:
    name: pihole-conf
    driver_options:
      type: none
      device: /var/pihole/dnsmasq.d
      o: bind
  when: deployment | lower == "greenfield"
- name: Pull PiHole docker image
  docker_image:
    name: "pihole/pihole:{{ _ph_version }}"
    source: pull
- name: Remove PiHole container
  docker_container:
    name: "{{ pi_name }}"
    state: absent
  when: deployment | lower == "brownfield"
