---
- hosts: pihole
  gather_facts: true
  become: true
  name: PiHole
  tasks:
    - name: Restore on failure
      block:
        - name: Install PiHole
          vars:
            _version: "{{ _ph_version }}"
            _task_name: "run PiHole in version: {{ _ph_version }}"
          ansible.builtin.import_role:
            name: pihole
      rescue:
        - name: Set PiHole restore variables
          ansible.builtin.set_fact:
            _version: "{{ _ph_restore_version }}"
            _task_name: "restore PiHole to version: {{ _ph_restore_version }}"
          when: deployment | lower == "brownfield"
        - name: Restore on fail
          ansible.builtin.import_role:
            name: pihole
          when: deployment | lower == "brownfield" and installation_type | lower == "docker"
