---
- ansible.builtin.import_playbook: playbooks/check_deploy.yml
- ansible.builtin.import_playbook: playbooks/prepare.yml
  when: deployment | lower == "greenfield"
- ansible.builtin.import_playbook: playbooks/backup.yml
  when: deployment | lower == "brownfield"
- ansible.builtin.import_playbook: playbooks/pihole.yml
- ansible.builtin.import_playbook: playbooks/restore_from_backup.yml
  when: deployment | lower == "greenfield"
