---
- include: playbooks/check_deploy.yml
- include: playbooks/prepare.yml
  when: deployment | lower == "greenfield"
- include: playbooks/backup.yml
  when: deployment | lower == "brownfield"
- include: playbooks/pihole.yml
- include: playbooks/restore_from_backup.yml
  when: deployment | lower == "greenfield"
