all:
  children:
    linux:
      vars:
        ansible_ssh_user: username
        ansible_ssh_pass: password
        ansible_port: 22
        #ansible_ssh_private_key_file: <path_to_key>
      children:
        pihole:
          hosts:
            127.0.0.1:
