---
- hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: check deployment
      debug:
        msg: "Deployment: {{ deployment | lower }}."
      failed_when: deployment | lower not in [ "greenfield", "brownfield" ]
    - name: check if send backup is selected
      debug:
        msg: 
          - "Send to Azure: {{ _azure_upload }}"
          - "Send to Linode: {{ _linode_upload }}"
      failed_when: _azure_upload >= 2 and _linode_upload >= 2 or _azure_upload >= 2 or _linode_upload >= 2
      when: deployment | lower == "brownfield"
    - name: check if restore from backup is selected
      debug:
        msg: 
          - "Restore from Azure: {{ _restore_from_backup.azure }}"
          - "Restore from Linode {{ _restore_from_backup.linode }}"
      failed_when: _restore_from_backup.azure >= 1 and _restore_from_backup.linode >= 1 or _restore_from_backup.azure >= 2 or _restore_from_backup.linode >= 2
      when: deployment | lower == "greenfield"
