---
- hosts: pihole
  gather_facts: true
  become: true
  tasks:
    - block:
        - name: install PiHole
          import_role:
            name: roles/pihole
      rescue:
        - name: do not restore in greenfield
          fail:
            msg: "Installation failed!"
          when: deployment | lower == "greenfield"
        - name: restore on fail
          include_role:
            name: roles/restore
          when: deployment | lower == "brownfield"
