name: Test docker image
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

env:
  GH_TOKEN: ${{ secrets.token }}
  DISCORD: ${{ secrets.discord_webhook }}

jobs:
  test:
    name: Test Docker image
    runs-on: ubuntu-latest
    container: docker:stable
    steps:
#      - name: Checkout pihole repository
#        uses: actions/checkout@v4
#        with:
#          repository: ${{ github.repository }}
#          ref: ${{ github.ref }}
#          token: ${{ env.GH_TOKEN }}

      - name: Git Version
        id: version
        uses: codacy/git-version@2.4.0

      - name: Test
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          push: false
          tags: moleszek/pihole:${{ steps.version.outputs.version }}
