---
- name: set pihole dns
  lineinfile:
    state: present
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: 'nameserver {{ ansible_default_ipv4.address }}'
  when: deployment | lower == "greenfield"
- name: remove old PiHole docker image
  docker_image:
    state: absent
    name: pihole/pihole
    tag: "v{{ _ph_restore_version }}"
  when: deployment | lower == "brownfield"