---
- name: "create PihHole docker network"
  docker_network:
    name: "{{ pi_net }}"
    state: present
  when: deployment | lower == "greenfield"
- name: "pull PiHole docker image"
  docker_image:
    name: "pihole/pihole:v{{ _ph_version }}"
- name: "remove PiHole container"
  docker_container:
    name: "{{ pi_name }}"
    state: absent
  when: deployment | lower == "brownfield"