---
- name: create PiHole docker network
  docker_network:
    name: "{{ pi_net }}"
    state: present
  when: deployment | lower == "greenfield"
- name: create PiHole folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  with_items:
    - "{{ pi_folders }}"
  when: deployment | lower == "greenfield"
- name: create PiHole pihole volume
  docker_volume:
    name: pihole-db
    driver_options:
      type: none
      device: /var/pihole/pihole
      o: bind
  when: deployment | lower == "greenfield"
- name: create PiHole config-pihole volume
  docker_volume:
    name: pihole-conf
    driver_options:
      type: none
      device: /var/pihole/dnsmasq.d
      o: bind
  when: deployment | lower == "greenfield"
- name: create PiHole log volume
  docker_volume:
    name: pihole-log
    driver_options:
      type: none
      device: /var/pihole/logs
      o: bind
  when: deployment | lower == "greenfield"
- name: pull PiHole docker image
  docker_image:
    name: "pihole/pihole:v{{ _ph_version }}"
- name: remove PiHole container
  docker_container:
    name: "{{ pi_name }}"
    state: absent
  when: deployment | lower == "brownfield"
